### ISSUE TITLE
Static lib not installed

### ISSUE THREAD

**Issue by nitsch** [thp/psmoveapi#256]
The static lib is built but not part of the install targets.

**Comment by thp** [comment]
That's correct, and I guess is the intended way so that by default, distribution packages link against the shared library and not accidentally link against the static library. If somebody wants to statically link against PS Move API, they probably build it with a specific configuration and link it in their build system and not from the system installation directory.

If you feel that it's useful to also install the static library, I'm happy to accept a pull request :)

**Comment by thp** [comment]
Closing for now, only the shared library should be installed, the static library should only be used in custom builds, not installed system-wide.
