### ISSUE TITLE
Two Python APIs

### ISSUE THREAD

**Issue by nitsch** [thp/psmoveapi#338]
https://github.com/thp/psmoveapi/issues/335#issuecomment-350709347 mentions ctypes-based Python bindings, and indeed, some scripts in examples/python/ use this new API.

What are the plans for the Python bindings? Is the new API supposed to eventually replace the SWIG-based one? Having two different APIs for the same thing is likely to generate some confusion.

**Comment by thp** [comment]
Yes, it's expected that the new bindings in https://github.com/thp/psmoveapi/blob/master/bindings/python/psmoveapi.py are the ones that should be used for future projects. The new bindings mirror the new C/C++-based API in https://github.com/thp/psmoveapi/blob/master/include/psmoveapi.h -- however, not all low-level functions are mapped by this API yet (and might not ever be), so that's why the old ones will probably still hang around a little longer.
