### ISSUE TITLE
Issue with running python scripts

### ISSUE THREAD

**Issue by rdFoe** [thp/psmoveapi#355]
Hi,

I downloaded the latest version and built it for windows. When I want to run one of the python test scripts (for example always.py) I get the error "psmove modul not found". Did I miss something?

**Comment by thp** [comment]
How did you build it? What does the `cmake` configure output show? You probably have to install Python and the [SWIG](http://www.swig.org/download.html) binary first before running cmake, so that it can pick up the path to those tools.

Alternatively, with the latest version, you can also just use the DLL + the `ctypes`-based [psmoveapi.py](https://github.com/thp/psmoveapi/blob/master/bindings/python/psmoveapi.py) without the need to build the bindings with SWIG. The API is a bit different, the old examples won't work, but there's a new example here: [new_api_events.py](https://github.com/thp/psmoveapi/blob/master/examples/python/new_api_events.py)

**Comment by rdFoe** [comment]
Thanks for your quick response. I got it fixed! Had some errors with the SWIG bindings but got it fixed already.

**Comment by thp** [comment]
Cool! Closing this issue. Feel free to open another one if you still got issues with the API.
